### ISSUE TITLE
Include full sound-library

### ISSUE THREAD

**Issue by VSU-ghall** [VSU-ghall/Supernova#59]
1. Have a full library of effect sounds such as lasers, background noises, enemy themes, and sounds for achievement, loses, and power ups.
3. Create a few custom sounds based on the level/ room the character is in.

**Comment by nkgarner** [comment]
I have created a full sound library with sound for main menu, background, jumping, collection rewards, dying, entity threats, and other sound effects to enhance the environment. This is just the initial library. I will work on getting more specific sounds as we design the level stories.
